# -*- coding: utf-8 -*-
"""build meta graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bK30PRBppwxR-oKGzyC64x72YsR0LIkR
"""

import networkx as nx
from itertools import permutations
import itertools
from collections import defaultdict
import networkx as nx
from itertools import combinations
from typing import List, Tuple, Dict, Any



def node_potential(graph, node, community, gamma):
    d_in = sum(1 for neighbor in graph.neighbors(node) if neighbor in community)
    n_k = len(community)
    return d_in - gamma * (n_k - (1 if node in community else 0))

def partition_potential(graph, partition, gamma):
    total = 0
    for community in partition:
        for node in community:
            total += node_potential(graph, node, community, gamma)
    return total / 2

def all_partitions(collection):
    if len(collection) == 1:
        yield [collection]
        return
    first = collection[0]
    for smaller in all_partitions(collection[1:]):
        for n, subset in enumerate(smaller):
            yield smaller[:n] + [[first] + subset] + smaller[n+1:]
        yield [[first]] + smaller

def normalize(partition):
    return tuple(sorted(tuple(sorted(comm)) for comm in partition))

# Fix the target community reference using new_communities
def build_meta_graph(G, gamma):
    meta = nx.DiGraph()
    nodes = list(G.nodes())
    all_parts = list(all_partitions(nodes))
    potentials = {}

    for part in all_parts:
        norm = normalize(part)
        meta.add_node(norm)
        potentials[norm] = partition_potential(G, [set(c) for c in norm], gamma)

    for part in all_parts:
        current = normalize(part)
        communities = [set(c) for c in current]
        for i, comm in enumerate(communities):
            for node in comm:
                for j, target_comm in enumerate(communities):
                    if i == j:
                        continue
                    new_communities = [set(c) for c in communities]
                    new_communities[i].remove(node)
                    new_communities[j].add(node)
                    if not new_communities[i]:
                        new_communities.pop(i)
                        if i < j:
                            j -= 1
                    new_norm = normalize(new_communities)

                    if new_norm not in potentials:
                        potentials[new_norm] = partition_potential(G, [set(c) for c in new_norm], gamma)

                    gain = potentials[new_norm] - potentials[current]
                    if gain > 0:
                        # get source and destination communities from new_communities
                        source_comm = comm
                        target_comm = new_communities[j]
                        neighbors_before = sum(1 for nbr in G.neighbors(node) if nbr in source_comm)
                        non_neighbors_before = len(source_comm) - 1 - neighbors_before
                        neighbors_after = sum(1 for nbr in G.neighbors(node) if nbr in target_comm)
                        non_neighbors_after = len(target_comm) - 1 - neighbors_after
                        meta.add_edge(current, new_norm, moved_node=node,
                                      gain=gain,
                                      neigh_before=neighbors_before,
                                      non_before=non_neighbors_before,
                                      neigh_after=neighbors_after,
                                      non_after=non_neighbors_after)
    return meta, potentials

def filter_best_response_edges(meta_graph):
    best_graph = nx.DiGraph()
    best_graph.add_nodes_from(meta_graph.nodes(data=True))

    for node in meta_graph.nodes:
        out_edges = list(meta_graph.out_edges(node, data=True))
        if not out_edges:
            continue
        max_gain = max(data['gain'] for _, _, data in out_edges)
        for u, v, data in out_edges:
            if abs(data['gain'] - max_gain) < 1e-6:
                best_graph.add_edge(u, v, **data)

    return best_graph

def shortest_path_to_equilibrium(start_partition, meta_graph):
    normalized_start = tuple(sorted(tuple(sorted(c)) for c in start_partition))
    if normalized_start not in meta_graph:
        raise ValueError("Start partition not found in the meta-graph.")

    sink_nodes = [node for node in meta_graph.nodes if meta_graph.out_degree(node) == 0]

    shortest = None
    min_len = float("inf")
    for sink in sink_nodes:
        try:
            path = nx.shortest_path(meta_graph, source=normalized_start, target=sink)
            if len(path) < min_len:
                min_len = len(path)
                shortest = path
        except nx.NetworkXNoPath:
            continue

    return shortest if shortest else None

def display_path_details(path, meta_graph):
    steps = []
    for i in range(len(path) - 1):
        u, v = path[i], path[i + 1]
        data = meta_graph.edges[u, v]
        step = {
            "from": u,
            "to": v,
            "moved_node": data['moved_node'],
            "neigh_before": data['neigh_before'],
            "non_before": data['non_before'],
            "neigh_after": data['neigh_after'],
            "non_after": data['non_after'],
            "gain": data['gain']
        }
        steps.append(step)
    return steps

def search_detailed_examples(max_nodes=4, gamma_values=[0.1, 0.25, 0.5, 0.75, 0.9]):
    examples = []

    for edges in itertools.combinations(combinations(range(max_nodes), 2), r=max_nodes):
        G = nx.Graph()
        G.add_edges_from(edges)
        if nx.is_connected(G):
            for gamma in gamma_values:
                meta_graph, potentials = build_meta_graph(G, gamma)
                best_graph = filter_best_response_edges(meta_graph)
                for start in meta_graph.nodes:
                    try:
                        br_path = shortest_path_to_equilibrium(start, meta_graph)
                        best_path = shortest_path_to_equilibrium(start, best_graph)
                        if br_path and best_path and len(br_path) < len(best_path):
                            example = {
                                "edges": list(G.edges),
                                "gamma": gamma,
                                "start_partition": start,
                                "better_steps": len(br_path) - 1,
                                "best_steps": len(best_path) - 1,
                                "better_path_details": display_path_details(br_path, meta_graph),
                                "best_path_details": display_path_details(best_path, best_graph),
                                "final_better_partition": br_path[-1],
                                "final_best_partition": best_path[-1]
                            }
                            examples.append(example)
                    except Exception:
                        continue
            if examples:
                break
    return examples

examples_detailed = search_detailed_examples()
examples_detailed